### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by kawax** [kawax/laravel-vercel-installer#1]
いくつかファイルをコピーするだけとはいえ段々面倒になってきたのでインストーラーを作った。

ただし現時点では「composerのキャッシュがない状態」でデプロイするとエラーが出る。
原因はvercel-phpなのかどれかのcomposerパッケージなのか不明。
PHPを含まないプロジェクトでは発生しない。

**Comment by kawax** [comment]
Laravelもcomposerもなし、vercel-phpのみの簡単なPHPファイルで発生。
vercel-phpがなければ発生しない。

**Comment by adnan-jamil** [comment]
Hi there, I am facing this error. If you built successfully, please share English version on how to resolve this error.

**Comment by kawax** [comment]
Maybe resolved.

しばらく様子を見てたけど最近はデプロイ成功してるのでたぶん解決。
